# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 879d13fb448615a8456f8c27f52b3372a3dfdfc24a3bbf037d198f1570dcdb0bba68f4bf79923ff78694d82185ba350316b11c8e2054dcc5c7a6ee6dc4c2d871

test:
  secret_key_base: 43dc905763e1029b2eae876b3cac6eb9a162f696d691f2ffdbfb9ed5025cea1ef5c9d5368ab889562e606e4a24deba9337f19eafaf33001ead923385d370b048

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
